### PR TITLE
Fix UB on MacOS: use 16 (not 8) byte offset in debug_size_heap

### PR DESCRIPTION
**Pull request by jzrake**
Would resolve issue https://github.com/arximboldi/immer/issues/74

### CODE REVIEW

**Comment by arximboldi** [comment]
Hi!

Thanks for submitting the patch and all the investigation involved!

As I explained in my response to #74, the proper fix requires a bit more of work. What I don't like about this PR is that it is not portable and just magically makes the UB disappear for your platform. Since the "proper" fix involves touching the `heap` API it needs a bit more thinking on my side. 

However, you can change your commit to just align to `alignof(std::max_align_t)`. I think the code would look like this (haven't tried it yet):
```cpp
    constexpr static auto extra_size = sizeof(std::aligned_storage<sizeof(std::size_t), alignof(std::max_align_t)>);

    template <typename... Tags>
    static void* allocate(std::size_t size, Tags... tags)
    {
        auto p = (std::size_t*) Base::allocate(size + extra_size, tags...);
        *p = size;
        return ((char*)p) + extra_size;
    }

    template <typename... Tags>
    static void deallocate(std::size_t size, void* data, Tags... tags)
    {
        auto p = (std::size_t*) (((char*) data) - extra_size);
        assert(*p == size);
        Base::deallocate(size + extra_size, p, tags...);
    }
```
Can you give it a try?

**Comment by arximboldi** [comment]
Also, note that the `free_list` heap family is working just because we are lucky... I can fix those later myself if you just want to merge this sooner so you can merge progress.

**Comment by jzrake** [comment]
Ok - there's an update to the PR.

Let me know if/how I can help in resolving similar issues to the `free_lists`'s.

**Comment by arximboldi** [comment]
Did this version fix it on your machine?

**Comment by arximboldi** [comment]
(It seems there are issues on Travis ;) )

**Comment by jzrake** [comment]
Oh no! Yes, (my own) basic examples work on my machine as of c106d27426f47aad47f2a7a3e24b78e9b7fda92b. How can I run the full test suite locally?

**Comment by arximboldi** [comment]
Seems to be working now. Thanks a lot for working through PR!
I hope you enjoy using Immer, looking forward to hear more about what you build with it :smile:

**Pull request merged**
