### PR TITLE
Tny vs2017

### PR DESCRIPTION
**Pull request by tnovotny**
I hope this is what you wanted. This is what I used to run the unit tests. Lemme know if there are any questions / issues.

### CODE REVIEW

**Comment by tnovotny** [comment]
This was just a quick way to get VS2017 to accept the CMake file. I use the File|Open|CMake... to open it. I  downloaded and build the gc-7.6.0 and build all libs with CMake and left them in the [x86|x64]-[Release|Debug] dirs. I changed the paths in the CMake file manually. Same goes for the boost stuff. I justed pointed CMake to the location.

**Comment by tereshkin** [comment]
I've tried this request but still got many compilation errors which I fixed manually. Some of them looked like restrictions of c++14 (I wasn't able to use c++17). But also I had many warnings for unused variables and type conversion (from `count_t` to `size_t`).

In the end I managed to get something working for flex_vector<T>. However the numeric result were Ok the unit test system reported some memory leaks.

**Comment by tnovotny** [comment]
What version of the compiler are you using? I tested with 15.5 preview and the 15.4.4.

**Comment by arximboldi** [comment]
Hi! What is the state of this one? Do you think you have time to make it work? Are you using the library on some Vistual Studio projects at the moment?

**Comment by tnovotny** [comment]
I have not made any further changes. I continually retry the version with every build that comes out, both VS 2017 and VS 2017 Preview, but unfort. there are still crashes with the set and map tests (Integer Division by Zero in dada.h). You said that you would look into it, 

> Can you push your code to a branch so I can give it a try?

Which is what I did.

> I have a few hypotheses on what the problem can be but it's probably
fastest if I just try it out myself.

so I was kind of hoping for some feedback from you.

**Comment by arximboldi** [comment]
tnovotny <notifications@github.com> writes:

> I have not made any further changes. I continually retry the version with every build that comes out, both VS 2017 and VS 2017 Preview, but unfort. there are still crashes with the set and map tests (Integer Division by Zero in dada.h). You said that you would look into it, 
>
>> Can you push your code to a branch so I can give it a try?
>
> Which is what I did.
>
>> I have a few hypotheses on what the problem can be but it's probably
> fastest if I just try it out myself.
>
> so I was kind of hoping for some feedback from you.

Hi, thanks for the reminder :)  I'll look into that, sorry it took me so
long to get back to you!

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by arximboldi** [comment]
#60 supersedes this PR. Thanks y'all for your contributions!

**Pull request closed without merging**
